CREATE OR REPLACE TRIGGER CHECKSEATLIMIT
BEFORE INSERT OR UPDATE ON CONNECTIONS
FOR EACH ROW
DECLARE
    SEAT_LIMIT INTEGER;
BEGIN
    SELECT SEAT_LIMIT INTO SEAT_LIMIT FROM CONNECTIONS WHERE FLIGHT_NO = :new.FLIGHT_NO;

    IF(SEAT_LIMIT <= 0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'No Seat Left');
    ELSE
        UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT - 1 WHERE FLIGHT_NO = :new.FLIGHT_NO;
    END IF;
END;
