CREATE OR REPLACE TRIGGER CHECKSEATLIMIT
BEFORE INSERT OR UPDATE ON BOOKING, CONNECTION
FOR EACH ROW
  DECLARE
    SeatNum INTEGER;
BEGIN
  SELECT SEAT_LIMIT INTO SeatNum FROM FLIGHT, CONNECTION
    WHERE FLIGHT.FLIGHT_NO = CONNECTION.FLIGHT_NO;
  IF (SeatNum <= 0) THEN
      RAISE_APPLICATION_ERROR(-20000, 'No Seat Left')
  ELSE
      UPDATE FLIGHT
  END IF;
END;
