CREATE TABLE BOOKINGS (
    ID INT,
    CUSTOMER_ID CHAR(6),
    FARE INT,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
)

CREATE OR REPLACE TRIGGER BOOKING_ID_INC
BEFORE INSERT ON BOOKINGS
FOR EACH ROW
BEGIN
    SELECT (COUNT(*) + 1) INTO :new.ID FROM BOOKINGS;
END;
