CREATE OR REPLACE TRIGGER CANCELBOOKING
AFTER DELETE ON BOOKINGS
FOR EACH ROW
BEGIN
    UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT + 1 WHERE FLIGHT_NO IN (SELECT FLIGHT_NO FROM CONNECTIONS WHERE ID = :old.ID);
    DELETE FROM CONNECTIONS WHERE ID = :old.ID;
END;