CREATE OR REPLACE TRIGGER CANCELBOOKING
AFTER DELETE ON BOOKINGS
FOR EACH ROW
BEGIN
    UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT + 1 WHERE FLIGHT_NO IN (SELECT FLIGHT_NO FROM CONNECTIONS WHERE ID = :old.ID);
    DELETE FROM CONNECTIONS WHERE ID = :old.ID;
END;

/*
CREATE OR REPLACE TRIGGER CANCELBOOKING
BEFORE DELETE ON BOOKINGS
FOR EACH ROW
DECLARE
    EXISTENCE INTEGER;
BEGIN
--     SELECT COUNT(*) INTO EXISTENCE FROM CONNECTIONS WHERE FLIGHT_NO = :new.FLIGHT_NO;
--     IF(EXISTENCE = 0) THEN
--         RAISE_APPLICATION_ERROR(-20000, 'Tuple Not Exist');
--     ELSE
        UPDATE FLIGHTS SET SEAT_LIMIT = SEAT_LIMIT + 1 WHERE FLIGHT_NO = :new.FLIGHT_NO;
--     END IF;
END;

 */