CREATE TABLE FLIGHTS (
    FLIGHT_NO VARCHAR(8) NOT NULL,
    DEPART_TIME DATE NOT NULL,
    ARRIVE_TIME DATE NOT NULL,
    FARE INT NOT NULL,
    SEAT_LIMIT INT NOT NULL,
    SOURCE VARCHAR(32) NOT NULL,
    DEST VARCHAR(32) NOT NULL,
    PRIMARY KEY(FLIGHT_NO)
)