CREATE TABLE BOOKINGS (
    ID INT NOT NULL,
    CUSTOMER_ID CHAR(6) NOT NULL,
    FARE REAL NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(ID) ON DELETE CASCADE
)