CREATE TABLE FLIGHTS (
    FLIGHT_NO VARCHAR(8),
    DEPART_TIME DATE,
    ARRIVE_TIME DATE,
    FARE INT,
    SEAT_LIMIT INT,
    SOURCE VARCHAR(32),
    DEST VARCHAR(32),
    PRIMARY KEY(FLIGHT_NO)
)