CREATE OR REPLACE TRIGGER DELETE_FLIGHT_TRIGGER
BEFORE DELETE ON FLIGHTS
FOR EACH ROW
BEGIN
    DELETE FROM CONNECTIONS WHERE FLIGHT_NO = :old.FLIGHT_NO;
END;

/* DELETE FROM BOOKINGS WHERE ID IN (SELECT DISTINCT ID FROM CONNECTIONS WHERE FLIGHT_NO = :old.FLIGHT_NO); */