CREATE OR REPLACE TRIGGER DELETE_FLIGHT_TRIGGER
BEFORE DELETE ON FLIGHTS
FOR EACH ROW
DECLARE
COUNTS INTEGER;
BEGIN
    SELECT COUNT(*) INTO COUNTS FROM CONNECTIONS WHERE FLIGHT_NO = :old.FLIGHT_NO;

    IF(COUNTS > 0) THEN
        RAISE_APPLICATION_ERROR(-20000, 'FLIGHT_HAS_CONNECTIONS');
    END IF;
END;