SELECT FLIGHT_NO, FARE
FROM FLIGHTS
WHERE SOURCE = ? AND DEST = ?
  AND (DEPART_TIME - ARRIVE_TIME) * 24 < ?;


SELECT F1.FLIGHT_NO, F2.FLIGHT_NO, F1.FARE+F2.FARE
FROM FLIGHTS F1, FLIGHTS F2
WHERE (F1.SOURCE = ? AND F2.DEST = ?)
  AND (F1.DEST = F2.SOURCE  AND F1.ARRIVE_TIME <= F2.DEPART_TIME)
  AND (F2.ARRIVE_TIME - F1.DEPART_TIME) * 24 < ?;

SELECT F1.FLIGHT_NO, F2.FLIGHT_NO, F3.FLIGHT_NO, F1.FARE+F2.FARE+F3.FARE
FROM FLIGHTS F1, FLIGHTS F2, FLIGHTS F3
WHERE (F1.SOURCE = ? AND F3.DEST = ?)
  AND(F1.DEST = F2.SOURCE AND F1.ARRIVE_TIME <= F2.DEPART_TIME)
  AND(F2.DEST = F3.SOURCE AND F2.ARRIVE_TIME <= F3.DEPART_TIME)
  AND(F3.ARRIVE_TIME - F1.DEPART_TIME) * 24 < ?;